change in the conditional in worflow and a task en gradle

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,7 +45,6 @@ jobs:
                 -Dsonar.organization=${{ secrets.SONAR_ORG }} \
                 -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                 -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
-                -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
       - name: Wait for Quality Gate result
         id: sonarqube-quality-gate-check
         uses: sonarsource/sonarqube-quality-gate-action@master
@@ -53,8 +52,11 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-      - name: Show SonarQube Quality Gate Status value
-        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+      - name: Fail pipeline if Quality Gate failed
+        if: steps.sonarqube-quality-gate-check.outputs.quality_gate_status != 'PASSED'
+        run: |
+          echo "❌ Quality Gate FAILED. Stop pipeline."
+          exit 1
 
   build-and-push:
     runs-on: ubuntu-latest
