modify worflow in sonarcloud

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,25 +38,29 @@ jobs:
       - name: jacoco
         run: ./gradlew clean test jacocoTestReport
 
-      - name: SonarCloud Scan
-        run: |
-            ./gradlew sonar \
-                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
-                -Dsonar.organization=${{ secrets.SONAR_ORG }} \
-                -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-                -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
-      - name: Wait for Quality Gate result
-        id: sonarqube-quality-gate-check
-        uses: sonarsource/sonarqube-quality-gate-action@master
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      - name: Run SonarCloud analysis
+        uses: SonarSource/sonarcloud-github-action@master
+        with:
+          args: >
+            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
+            -Dsonar.organization=${{ secrets.SONAR_ORG }}
+            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
 
-      - name: Fail pipeline if Quality Gate failed
-        if: steps.sonarqube-quality-gate-check.outputs.quality_gate_status != 'PASSED'
+      - name: Wait for Quality Gate status
         run: |
-          echo "❌ Quality Gate FAILED. Stop pipeline."
-          exit 1
+            echo "Checking Quality Gate status..."
+            QUALITY_GATE_STATUS=$(curl -s -X GET -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")
+            echo "Quality Gate status: $QUALITY_GATE_STATUS"
+            # Verifica si el estado es 'OK' o 'ERROR'
+            if [[ $QUALITY_GATE_STATUS == *'"status":"OK"'* ]]; then
+              echo "Quality Gate Passed"
+            else
+              echo "Quality Gate Failed"
+              exit 1
+            fi
+
 
   build-and-push:
     runs-on: ubuntu-latest
